# Generated by Django 4.2.27 on 2026-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaapp', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenGem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('place', 'Place'), ('food', 'Food'), ('story', 'Story'), ('photo', 'Photo')], max_length=20)),
                ('description', models.TextField()),
                ('how_to_find', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('difficulty_accessibility', models.CharField(blank=True, max_length=60)),
                ('contributor_name', models.CharField(max_length=120)),
                ('contributor_profile', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('moderator_notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, to='mediaapp.photo')),
                ('tags', models.ManyToManyField(blank=True, to='places.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
