# Generated by Django 4.2.27 on 2026-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaapp', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location_text', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=120)),
                ('event_type', models.CharField(choices=[('aarti', 'Aarti'), ('festival', 'Festival'), ('cultural', 'Cultural'), ('market', 'Market'), ('other', 'Other')], default='other', max_length=20)),
                ('ticket_link', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, to='mediaapp.photo')),
                ('related_places', models.ManyToManyField(blank=True, to='places.place')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
