# Generated by Django 4.2.27 on 2026-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaapp', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('dish_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('snack', 'Snack'), ('sweet', 'Sweet'), ('drink', 'Drink'), ('meal', 'Meal')], max_length=20)),
                ('origin_story', models.TextField(blank=True)),
                ('spice_level', models.CharField(blank=True, max_length=20)),
                ('best_time', models.CharField(blank=True, max_length=80)),
                ('recommended_stalls', models.JSONField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, to='mediaapp.photo')),
                ('tags', models.ManyToManyField(blank=True, to='places.tag')),
                ('where_to_eat', models.ManyToManyField(blank=True, to='places.place')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
