# Generated by Django 4.2.27 on 2026-01-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='crowd_level',
            field=models.PositiveSmallIntegerField(default=3, help_text='1: Quiet, 5: Very Busy'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_elderly_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
