# Generated by Django 4.2.27 on 2026-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('location_text', models.CharField(blank=True, max_length=200)),
                ('photographer', models.CharField(blank=True, max_length=120)),
                ('copyright', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('image_file', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
