# Generated by Django 4.2.27 on 2026-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaapp', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('product_types', models.JSONField(blank=True, null=True)),
                ('owner_story', models.TextField(blank=True)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('best_products', models.TextField(blank=True)),
                ('contact', models.JSONField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('photos', models.ManyToManyField(blank=True, to='mediaapp.photo')),
                ('tags', models.ManyToManyField(blank=True, to='places.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
