# Generated by Django 4.2.27 on 2026-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('type', models.CharField(choices=[('ghat', 'Ghat'), ('temple', 'Temple'), ('shop', 'Shop'), ('alley', 'Alley'), ('museum', 'Museum'), ('other', 'Other')], max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('neighbourhood', models.CharField(max_length=80)),
                ('short_description', models.CharField(max_length=160)),
                ('long_description', models.TextField(blank=True)),
                ('history_story', models.TextField(blank=True)),
                ('open_hours', models.JSONField(blank=True, null=True)),
                ('entry_fee', models.CharField(blank=True, max_length=60)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=80)),
                ('visitor_tips', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('schema_type', models.CharField(default='Place', max_length=40)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, to='mediaapp.photo')),
                ('tags', models.ManyToManyField(blank=True, to='places.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
