# Generated by Django 4.2.27 on 2026-01-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaapp', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('author_name', models.CharField(max_length=120)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('publish_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaapp.photo')),
                ('related_places', models.ManyToManyField(blank=True, to='places.place')),
                ('tags', models.ManyToManyField(blank=True, to='places.tag')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
