# Generated by Django 4.2.27 on 2026-01-22 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('trust_score', models.IntegerField(default=0)),
                ('verified_badge', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
